version: '3.8'

services:
  web:
    container_name: ordem-servico-flask
    build:
      context: .
      args:
        UID: ${UID:-1000}
        USER: ${USER:-flaskuser}
    env_file:
      ./.env
    networks:
      - npm
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
networks:
  npm:
    external: true